name: Dump controls

on:
  workflow_dispatch:

jobs:
  dump-controls:

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Dump controls
        run: |
          ./dump-controls > security-hub-controls.jsonl
      
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

    permissions:
      contents: write
    
    runs-on: ubuntu-latest
